"""add saldo_a_favor to clientes

Revision ID: 170a570f7cd9
Revises: 8ba42dbe497a
Create Date: 2026-07-18 23:43:17.845894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170a570f7cd9'
down_revision = '8ba42dbe497a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_a_favor', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('saldo_a_favor')

    # ### end Alembic commands ###
