"""add vales column to arqueos

Revision ID: 2919e6c334fe
Revises: 170a570f7cd9
Create Date: 2026-07-19 00:14:18.539211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2919e6c334fe'
down_revision = '170a570f7cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vales', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueos', schema=None) as batch_op:
        batch_op.drop_column('vales')

    # ### end Alembic commands ###
