"""esquema inicial

Revision ID: 7698191edb77
Revises: 
Create Date: 2026-07-18 21:13:15.946641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7698191edb77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arqueos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cajero', sa.String(length=160), nullable=False),
    sa.Column('turno', sa.String(length=40), nullable=False),
    sa.Column('fondo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conteos', sa.JSON(), nullable=False),
    sa.Column('no_efectivo', sa.JSON(), nullable=False),
    sa.Column('facturas_contado', sa.JSON(), nullable=False),
    sa.Column('facturas_credito', sa.JSON(), nullable=False),
    sa.Column('totales', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arqueos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arqueos_fecha'), ['fecha'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('rnc_cedula', sa.String(length=40), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_rnc_cedula'), ['rnc_cedula'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_telefono'), ['telefono'], unique=False)

    op.create_table('conduces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=160), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('factura', sa.String(length=60), nullable=True),
    sa.Column('bultos', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=60), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADA', name='estado_factura'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'numero', name='uq_factura_cliente_numero')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_numero'), ['numero'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_fecha'), ['fecha'], unique=False)

    op.create_table('detalle_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalle_pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalle_pagos_factura_id'), ['factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalle_pagos_pago_id'), ['pago_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_pagos_pago_id'))
        batch_op.drop_index(batch_op.f('ix_detalle_pagos_factura_id'))

    op.drop_table('detalle_pagos')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_fecha'))
        batch_op.drop_index(batch_op.f('ix_pagos_cliente_id'))

    op.drop_table('pagos')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_numero'))
        batch_op.drop_index(batch_op.f('ix_facturas_estado'))
        batch_op.drop_index(batch_op.f('ix_facturas_cliente_id'))

    op.drop_table('facturas')
    op.drop_table('conduces')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_telefono'))
        batch_op.drop_index(batch_op.f('ix_clientes_rnc_cedula'))
        batch_op.drop_index(batch_op.f('ix_clientes_nombre'))

    op.drop_table('clientes')
    with op.batch_alter_table('arqueos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arqueos_fecha'))

    op.drop_table('arqueos')
    # ### end Alembic commands ###
