"""cobros informales final

Revision ID: a2630c95d949
Revises: dd95ec70c1f3
Create Date: 2026-07-18 22:15:21.808985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2630c95d949'
down_revision = 'dd95ec70c1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobros_informales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', name='estado_cobro_informal'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cobros_informales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobros_informales_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobros_informales_estado'), ['estado'], unique=False)

    op.create_table('abonos_cobro_informal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cobro_informal_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'CHEQUE', 'TRANSFERENCIA', 'TARJETA', name='forma_pago_informal'), nullable=False),
    sa.Column('banco', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=60), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['cobro_informal_id'], ['cobros_informales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abonos_cobro_informal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abonos_cobro_informal_cobro_informal_id'), ['cobro_informal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonos_cobro_informal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abonos_cobro_informal_cobro_informal_id'))

    op.drop_table('abonos_cobro_informal')
    with op.batch_alter_table('cobros_informales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobros_informales_estado'))
        batch_op.drop_index(batch_op.f('ix_cobros_informales_cliente_id'))

    op.drop_table('cobros_informales')
    # ### end Alembic commands ###
